### ISSUE TITLE
Error with artillery turrets in servers

### ISSUE THREAD

**Issue by javiburatos** [Warfactory-Official/Hbm-s-Nuclear-Tech-CE#1077]
### Describe the bug

Artillery turrets don't work properly on servers. The projectiles they fire, when aimed at distant chunks (around 200 blocks, within the turret's range), freeze and never hit the ground. This happens when using the radar and manual targeting mode. I assume it also happens with anything related to missiles or the orbital death ray that are launched remotely.

### Severity

Game-breaking (crash on startup/world load)

### Game Context

- [ ] Singleplayer
- [x] Multiplayer (dedicated server)
- [x] Creative
- [x] Survival

### Run URL

https://github.com/Warfactory-Offical/Hbm-s-Nuclear-Tech-CE/actions/runs/19598064303

### Confirmation

- [x] I reproduced this on the latest successful GitHub Actions build.

### To Reproduce

1.  Use an artillery turret in artillery mode
2.  Link this turret to a radar and select coordinates where the projectile should land.
3.  You can use a radar screen to see that the artillery shell freezes.

### Expected behavior

The projectile should land at the designated coordinates but it doesn't; sometimes it even glitches and keeps launching projectiles indefinitely.

### Are other mods present and is it a compatibility issue?

no

**Comment by NoPressF** [comment]
Can you record the video?

**Comment by javiburatos** [comment]
yes, give me a second

**Comment by javiburatos** [comment]
I tried a first test before recording the video and the artillery shell froze in the air and never fell, and now for the second test, which is the one you see in the video, the shell doesn't even launch.

Link to video (is google drive, github dont allow me to paste the video here) --> https://drive.google.com/file/d/1xsc2BhOLAMulLGx5e30AKGWr3ZgQVADx/view?usp=sharing

**Comment by NoPressF** [comment]
Did you try that on 1.7?

**Comment by javiburatos** [comment]
I haven't tried it because I thought the turret system should work. Should I try it?

**Comment by NoPressF** [comment]
Yes, you can try

**Comment by javiburatos** [comment]
give me a few hours so

**Comment by javiburatos** [comment]
It seems the problem is also present in version 1.7.

The issue is that when you launch an artillery shell from an area where the turret itself isn't loaded, the shell doesn't even fire.
I've opened an issue on the original version's GitHub repository in case they can do something about it. That said, I'm closing this bug report. Should I wait for their response, or can you fix it yourselves?

**Comment by NoPressF** [comment]
To be honest, I don't know. I can try to fix it when I find time for it

**Comment by javiburatos** [comment]
ok, i will wait. thanks!

**Comment by NoPressF** [comment]
I don't know why, but I launched the server and fired artillery at a long distance and the projectile landed successfully

**Comment by javiburatos** [comment]
xdddd, i will test it. give me a few hours

**Comment by javiburatos** [comment]
Okay, now I'm unable to use artillery mode in either single-player or multiplayer. Can you explain how you launch an artillery shell from a radar?

Note: I'm using the cleanroom (java25) version of the mod.

**Comment by NoPressF** [comment]
I can't launch arty shell with radar also. I'm using a Forge

**Comment by javiburatos** [comment]
so, this is the problem xd

**Comment by NoPressF** [comment]
It's also impossible to do this on 1.7.10, so I won't be able to do anything about it

**Comment by NoPressF** [comment]
Try launching artillery shells from several hundred blocks away

**Comment by javiburatos** [comment]
It still won't fire, but this happened. I tried to launch a projectile, it didn't launch, I exited the world, re-entered, and now it launched the projectile.

**Comment by NoPressF** [comment]
I didn't have this problem and the projectile launched on the first try

**Comment by javiburatos** [comment]
Okay, I haven't been able to replicate this. The truth is, I don't know how to launch artillery shells.

**Comment by javiburatos** [comment]
you use the artillery mode true?

**Comment by javiburatos** [comment]
and large or normal radar?

**Comment by NoPressF** [comment]
I launched without radar and used Manual mode

**Comment by javiburatos** [comment]
Yeah, but the problem is artillery mode.

**Comment by javiburatos** [comment]
i proved that in 1.7 and, at least, the cannon (greg) shot in artillery mode

**Comment by NoPressF** [comment]
I have fixed bug #449. So can you check if artillery projectile fires?

**Comment by javiburatos** [comment]
ok, give me a second

**Comment by javiburatos** [comment]
It still doesn't work. It's strange because when I opened this post (playing an older version of this mod), at least the turret was firing in artillery mode.

**Comment by NoPressF** [comment]
In artillery mode it says the minimum firing range is 250 meters. Have you tested it at that distance?

**Comment by javiburatos** [comment]
yes, above 500, 1000 and 1500 blocks distance and the cannon dont move

**Comment by NoPressF** [comment]
Honestly, I don't know if this is worth fixing because it doesn't seem worth it. The artillery will have to constantly turn around somewhere, and it will be somehow weird.

**Comment by javiburatos** [comment]
If you want, try it for yourself.

In a player world, connect an artillery turret to a radar and try to fire using this radar.

You'll see that the turret doesn't even move to launch the projectile. It simply does nothing.

**Comment by NoPressF** [comment]
I don't understand, are we discussing artillery fire from radar or?

**Comment by javiburatos** [comment]
yeah

**Comment by javiburatos** [comment]
If you want, I can record a video showing you the steps I take to get the error

**Comment by NoPressF** [comment]
In 1.7, you can't launch an artillery shell using radar, so it's not even a bug anymore, but more of a feature

**Comment by javiburatos** [comment]
Hmm, I'd swear it's possible. Let me check, give me a few minutes.

**Comment by javiburatos** [comment]
Okay, that's strange. In version 1.7, the artillery turret does fire, but it doesn't work properly. To make it work, you first have to use manual mode with the long-range artillery remote. After that, you can fire projectiles in artillery mode using the radar. Is there any other way to use artillery mode?

**Comment by NoPressF** [comment]
I checked it myself by following your steps and didn't find that the artillery shot worked through the radar screen

**Comment by NoPressF** [comment]
You can try to open an issue that you explain the problem in the original repository 1.7

**Comment by javiburatos** [comment]
I did it and the devs ignored me :(
I've replicated the problem again, setting up the following test environment:
- Cleanroom alpha 17 environment
- HBM version 2.5.0.5
- Greg turret in artillery mode, linked to a radar
I placed one player in position A and another in position B (the distance between A and B is 300m). I launched a projectile from A towards B, and the projectile leaves the turret but never reaches point B; it gets stuck in mid-air.
I saw that the log shows this, so I'm posting it here.

[latest.log](https://github.com/user-attachments/files/30099108/latest.log)

**Comment by NoPressF** [comment]
@javiburatos Can you record the video? I don't know how to launch projectile in artillery mode xD

**Comment by javiburatos** [comment]
its complicated xd, give me a second

**Comment by javiburatos** [comment]
https://drive.google.com/file/d/1_A2qOJaxS5vkjKMwa5OWheuqX1yAgKmU/view?usp=sharing
I had to do it in version 1.7.10 because I can't get it to launch in 1.12.2; sometimes it works and sometimes it doesn't, even when following the exact same steps, so I don't know what might be going wrong.
The video doesn't show the projectile's approach, but at the 10-second mark, it lands on the second radar.

**Comment by javiburatos** [comment]
Okay, problem solved. It turns out this error was happening because this functionality was part of "manual mode" rather than "artillery mode." I've tested it with that mode now, and it works perfectly.
