### ISSUE TITLE
Detonating a nuke in a dedicated server won't generate crater and will spam console.

### ISSUE THREAD

**Issue by whatsapp2** [Warfactory-Official/Hbm-s-Nuclear-Tech-CE#906]
### Describe the bug

I recently added the most recent GitHub build to my server and I stumbled upon nukes not causing block damage and spamming errors to the server console.
One of those errors looks like this:
```
[02:38:40] [Server thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:6845]: java.lang.Exception: Tried getting entities from giant bounding box of box[785.5, -940.5, -6189.5 -> 2785.5, 1059.5, -4189.5]
[02:38:40] [Server thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:6845]:       at net.minecraft.world.World.func_175674_a(World.java:6844)
[02:38:40] [Server thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:6845]:       at net.minecraft.world.World.mixinextras$bridge$func_175674_a$248(World.java)
[02:38:40] [Server thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:6845]:       at net.minecraft.world.World.wrapOperation$zfl001$unknown_owner$utReducedRadiusAABBCall(World.java:5607)
[02:38:40] [Server thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:6845]:       at net.minecraft.world.World.func_72839_b(World.java:3011)
[02:38:40] [Server thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:6845]:       at com.hbm.explosion.ExplosionNukeGeneric.dealDamage(ExplosionNukeGeneric.java:88)
[02:38:40] [Server thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:6845]:       at com.hbm.explosion.ExplosionNukeGeneric.dealDamage(ExplosionNukeGeneric.java:82)
[02:38:40] [Server thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:6845]:       at com.hbm.entity.logic.EntityNukeExplosionMK5.TickCentral_TrueOnUpdateTick(EntityNukeExplosionMK5.java:134)
[02:38:40] [Server thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:6845]:       at com.github.terminatornl.tickcentral.api.TickHub.trueOnUpdate(TickHub.java:56)
[02:38:40] [Server thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:6845]:       at com.github.terminatornl.laggoggles.Main.redirectOnUpdate(Main.java:105)
[02:38:40] [Server thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:6845]:       at com.hbm.entity.logic.EntityNukeExplosionMK5.func_70071_h_(EntityNukeExplosionMK5.java)
[02:38:40] [Server thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:6845]:       at net.minecraft.world.World.func_72866_a(World.java:1996)
[02:38:40] [Server thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:6845]:       at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
[02:38:40] [Server thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:6845]:       at net.minecraft.world.World.func_72870_g(World.java:1958)
[02:38:40] [Server thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:6845]:       at net.minecraft.world.World.func_72939_s(World.java:1762)
[02:38:40] [Server thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:6845]:       at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
[02:38:40] [Server thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:6845]:       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
[02:38:40] [Server thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:6845]:       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:399)
[02:38:40] [Server thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:6845]:       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[02:38:40] [Server thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:6845]:       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[02:38:40] [Server thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:6845]:       at java.base/java.lang.Thread.run(Thread.java:1474)
```
And when starting the server it will throw this line
```
[02:53:22] [Server thread/WARN] [universalmodcore]: Adding entity that was not wrapped correctly ed06a8b6-7cd1-496b-8429-8d4abeae795f - EntityNukeExplosionMK5['entity.entity_nuke_mk5.name'/19, l='BBOP', x=-1599.32, y=55.03, z=1641.65]
```

### Severity

Substantial (progression breaking / game affecting, non-crashing)

### Game Context

- [ ] Singleplayer
- [x] Multiplayer (dedicated server)
- [ ] Creative
- [ ] Survival

### Run URL

https://github.com/Warfactory-Offical/Hbm-s-Nuclear-Tech-CE/actions/runs/18544496641

### Confirmation

- [x] I reproduced this on the latest successful GitHub Actions build.

### To Reproduce

1. Join a server with this build
2. Detonate a nuke
3. Nuke won't generate crater

### Expected behavior

Nuke should generate crater

### Screenshots, videos, crash report, logs

Log file too big to upload/paste anywhere 1.35 GB of just errors spamming console.

### Are other mods present and is it a compatibility issue?

None involved with the bug report.

### Modlist

https://gist.github.com/whatsapp2/72d664532d8c317377506de8c8f490f9

### Additional context

Using Cleanroom 0.3.15, Java 25 on Windows 11

**Comment by mlbv** [comment]
should be fixed in daf059ceff39897aceb8ae9d937f48cd8ee0ccae, comment below if it persists.

**Comment by whatsapp2** [comment]
Using the [latest build](https://github.com/Warfactory-Offical/Hbm-s-Nuclear-Tech-CE/actions/runs/18602530543) in my server doesn't fix the error. Nuke crater is not generating although the errors related to the bounding box have disappeared from the log.
Also, no error will be logged when detonating a nuke.

**Comment by whatsapp2** [comment]
Nuke seems to be processing in the background too.

https://github.com/user-attachments/assets/05269161-cd4c-4cbf-a65d-ee89b7f2bd51

**Comment by MisterNorwood** [comment]
Looks like mixin issue possibly

**Comment by mlbv** [comment]
~~Could you specify the server used?~~
nvm, see fugue in your modlist so it must be cleanroom.
could you share the entire `debug.log`?

**Comment by whatsapp2** [comment]
Here it is. This one is the server debug log
[debug.log](https://github.com/user-attachments/files/22981365/debug.log)

**Comment by mlbv** [comment]
The log isn't helpful. Could you join our discord? I can provide a custom version of the mod with more logging to help trace the bug

**Comment by Solar-Dolphin** [comment]
also having this issue on my server

**Comment by Kuktar** [comment]
I am also having this issue. Have done a little testing but am down to help more. would love to see the nukes work. the shradium ones work. they insta delete blocks. its just the normal nukes not working. i have bugtesting background if u need extra hands for testing.

**Comment by mlbv** [comment]
@Kuktar of course, could you join our discord server?

**Comment by MisterNorwood** [comment]
I want to renew interest in this, I want to finally solve this issue.

**Comment by MisterNorwood** [comment]
<img width="1109" height="671" alt="Image" src="https://github.com/user-attachments/assets/32f56b66-5266-41ca-8703-79068c125fc6" />
According to poster, issue happens due to Valkyrien skies

**Comment by mlbv** [comment]
confirmed as valkyrien skies mod conflict

**Comment by DiddyBlud-67-Adrian-Eeffoc** [comment]
This also happens in singleplayer, not just server
