### ISSUE TITLE
NTM slab issues

### ISSUE THREAD

**Issue by Tiilikellari08** [Warfactory-Official/Hbm-s-Nuclear-Tech-CE#986]
### Describe the bug

NTM slabs can't be stacked properly and cause blocks behind them to be very dark.

### Severity

Minor (visual/UI issue, non-crashing)

### Game Context

- [x] Singleplayer
- [x] Multiplayer (dedicated server)
- [x] Creative
- [x] Survival

### Run URL

https://github.com/Warfactory-Offical/Hbm-s-Nuclear-Tech-CE/actions/runs/18938617325

### Confirmation

- [x] I reproduced this on the latest successful GitHub Actions build.

### To Reproduce

1. Place down NTM slabs with blocks behind them
2. Observe
1. Try to stack NTM slabs
2. Observe

### Expected behavior

I should be able to stack NTM slabs. There shouldn't be a dark area when having NTM slabs next to blocks.

### Screenshots, videos, crash report, logs

Trying to stack slabs
<img width="2560" height="1351" alt="Image" src="https://github.com/user-attachments/assets/7dcedeff-af88-47d9-98e4-016ac37609d3" />
Dark area behind slabs
<img width="2560" height="1351" alt="Image" src="https://github.com/user-attachments/assets/f96725ad-88df-463f-b697-c215c2f2ecfc" />

### Are other mods present and is it a compatibility issue?

No

### Modlist

NTM and HEI

### Additional context

Windows 11, Latest forge and java, Default configs.

**Comment by mlbv** [comment]
fixed in c0f5188260f22271e0a861698aad60f27d641b73

**Comment by Tiilikellari08** [comment]
Lighting bug still happens in https://github.com/Warfactory-Offical/Hbm-s-Nuclear-Tech-CE/actions/runs/19159503291 <img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/49c5491e-17b0-46a4-8caa-23ae3131c13e" />

**Comment by mlbv** [comment]
I can no longer reproduce this problem, please comment below if you can

**Comment by Tiilikellari08** [comment]
Still happens on https://github.com/Warfactory-Official/Hbm-s-Nuclear-Tech-CE/actions/runs/20663881094 with only NTM installed.

**Comment by mlbv** [comment]
fixed in d7e16674f21c3abc4f486412fdc99d4e68edf98d
